# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 1080)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.edit_say = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_say.setGeometry(QtCore.QRect(450, 30, 221, 31))
        self.edit_say.setObjectName("edit_say")
        self.btn_say = QtWidgets.QPushButton(self.centralwidget)
        self.btn_say.setGeometry(QtCore.QRect(680, 40, 75, 23))
        self.btn_say.setObjectName("btn_say")
        self.img_label_canvas = QtWidgets.QLabel(self.centralwidget)
        self.img_label_canvas.setGeometry(QtCore.QRect(0, 160, 811, 441))
        self.img_label_canvas.setStyleSheet("border: 2px solid black;")
        self.img_label_canvas.setText("")
        self.img_label_canvas.setObjectName("img_label_canvas")
        self.img_label_bt = QtWidgets.QLabel(self.centralwidget)
        self.img_label_bt.setGeometry(QtCore.QRect(0, 670, 811, 311))
        self.img_label_bt.setStyleSheet("border: 2px solid black;")
        self.img_label_bt.setText("")
        self.img_label_bt.setObjectName("img_label_bt")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(400, 630, 111, 16))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.edit_say.setText(_translate("MainWindow", "做一杯咖啡"))
        self.btn_say.setText(_translate("MainWindow", "说话"))
        self.label_5.setText(_translate("MainWindow", "语义地图"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
